#!/usr/bin/env ruby
#
# Git commit-msg hook.
#
# It checks following syntax:
# - starts with either a Capital letter or `[...]` (usually used to assign a context to the commit)
# - at least 4 chars and max 100

$regex = /([A-Z]|(\[[\w\d-]+\]))+.{4,100}/

message_file = ARGV[0]
message = File.read(message_file).strip

if !$regex.match(message)
  puts "Invalid git-commit message format. Please ensure your message starts with a capital letter (or a context form e.g.: '[mc]') and has at least 4 chars and max 100."
  exit 1
end

